# Archivo de configuración para el analizador de liquidez de Binance
symbol: 'BTCUSDT'
lookback_period: '3 days ago UTC' # Periodo para calcular máximos/mínimos
aggregation_level: 100.0        # Agregación para el libro de órdenes (en USD)

telegram:
  bot_token: '8487978871:AAGbQ46fjpQvNoTNUg6dO6Szvr4ZfuPrymg' # Reemplaza con el token de tu Bot de Telegram
  chat_id: '1058018241'         # Reemplaza con tu Chat ID o el de tu grupo
